/** Scoped Desktop prompt surfaces, using the host's semantic palette. */
export const promptStyles = `
.dp-dialog{--dp-bg:var(--dsw-alias-bg-layer-1,#fff);--dp-soft:var(--dsw-alias-bg-layer-2,#f6f7f9);--dp-fg:var(--dsw-alias-label-primary,#20242b);--dp-muted:var(--dsw-alias-label-secondary,#636975);--dp-line:var(--dsw-alias-border-primary,#e4e7ec);--dp-accent:var(--dsw-alias-brand-primary,#4168cc);box-sizing:border-box;width:min(780px,calc(100vw - 40px));max-height:min(680px,calc(100dvh - 64px));padding:0;border:1px solid var(--dp-line);border-radius:16px;background:var(--dp-bg);color:var(--dp-fg);box-shadow:0 24px 80px #0002,0 2px 8px #0001;font:14px/1.5 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;margin:auto;overflow:auto;color-scheme:inherit;animation:dp-enter .16s ease-out}
.dp-dialog::backdrop{background:#11182730;backdrop-filter:blur(2px)}.dp-dialog *{box-sizing:border-box}.dp-dialog h2,.dp-dialog h3,.dp-dialog p{margin:0}.dp-dialog svg{flex:none}.dp-header{display:flex;align-items:center;justify-content:space-between;padding:20px 24px 16px;gap:16px}.dp-heading{display:flex;align-items:center;gap:12px}.dp-heading h2{font-size:18px;line-height:1.4;font-weight:650;letter-spacing:-.3px}.dp-heading p{font-size:12px;color:var(--dp-muted);margin-top:3px}.dp-mark{display:grid;place-items:center;width:38px;height:38px;border:1px solid var(--dp-line);background:var(--dp-soft);border-radius:11px;color:var(--dp-accent)}
.dp-dialog button{font:inherit;cursor:pointer;transition:background .15s,border-color .15s;color:inherit}.dp-dialog button:disabled{opacity:.48;cursor:default}.dp-icon{width:32px;height:32px;display:grid;place-items:center;border:0;border-radius:8px;background:transparent;color:var(--dp-muted)!important}.dp-icon:hover,.dp-clear:hover{background:var(--dp-soft)}.dp-dialog :is(button,input,textarea):focus-visible{outline:2px solid var(--dp-accent);outline-offset:3px}.dp-button,.dp-primary{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:36px;padding:7px 13px;border:1px solid var(--dp-line);border-radius:8px;background:var(--dp-bg);font-size:13px!important;font-weight:550!important;white-space:nowrap}.dp-button:hover:not(:disabled){background:var(--dp-soft)}.dp-dialog .dp-primary{background:var(--dp-accent);border-color:transparent;color:#fff}.dp-primary:hover:not(:disabled){filter:brightness(.94)}
.dp-toolbar{display:flex;gap:12px;padding:0 24px 16px}.dp-search{display:flex;align-items:center;gap:9px;flex:1;min-width:0;border:1px solid var(--dp-line);background:var(--dp-soft);border-radius:9px;padding:0 11px;color:var(--dp-muted)}.dp-search:focus-within{border-color:var(--dp-accent)}.dp-search input{width:100%;min-width:0;height:38px;border:0;background:transparent;color:var(--dp-fg);font:inherit;outline:none!important}.dp-search input::placeholder{color:var(--dp-muted)}.dp-clear{border:0;background:transparent;display:grid;place-items:center;padding:2px;border-radius:4px}
.dp-tabs{display:flex;gap:18px;padding:0 24px;border-bottom:1px solid var(--dp-line)}.dp-tabs button{border:0;border-bottom:2px solid transparent;background:transparent;padding:0 0 10px;font-size:13px;color:var(--dp-muted);display:flex;gap:6px;align-items:center}.dp-tabs button[aria-pressed=true]{border-bottom-color:var(--dp-accent);color:var(--dp-fg);font-weight:600}.dp-tabs span{font-size:11px;padding:0 6px;background:var(--dp-soft);border-radius:5px;color:var(--dp-muted)}
.dp-workspace{display:grid;grid-template-columns:minmax(180px, .9fr) minmax(0,1.25fr);height:320px}.dp-list{padding:10px;overflow:auto;border-right:1px solid var(--dp-line)}.dp-row{width:100%;display:flex;align-items:flex-start;gap:10px;border:1px solid transparent;background:transparent;text-align:left;padding:12px 10px;border-radius:9px;margin-bottom:3px}.dp-row>span:last-child{min-width:0}.dp-row strong{display:block;overflow-wrap:anywhere;font-size:13px;font-weight:600}.dp-row small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--dp-muted);margin-top:4px;font-size:12px}.dp-row-icon{color:var(--dp-muted);padding-top:1px}.dp-row:hover{background:var(--dp-soft)}.dp-row[aria-pressed=true]{background:color-mix(in srgb,var(--dp-accent) 8%,var(--dp-bg));border-color:color-mix(in srgb,var(--dp-accent) 16%,var(--dp-line))}.dp-row[aria-pressed=true] .dp-row-icon{color:var(--dp-accent)}
.dp-preview{padding:20px 22px;overflow:auto}.dp-preview-title{display:flex;justify-content:space-between;gap:10px;color:var(--dp-muted);font-size:11px;margin-bottom:16px}.dp-preview h3{font-size:15px;font-weight:600;overflow-wrap:anywhere;margin-bottom:12px}.dp-preview pre{font:13px/1.8 inherit;font-family:inherit;font-size:13px;line-height:1.8;white-space:pre-wrap;overflow-wrap:anywhere;margin:0;color:var(--dp-fg)}
.dp-footer{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:14px 24px;border-top:1px solid var(--dp-line);background:var(--dp-soft)}.dp-footer>div{display:flex;gap:8px}.dp-shortcut{font-size:11px;color:var(--dp-muted)}.dp-shortcut span{margin-left:9px}.dp-empty,.dp-error-state{min-height:260px;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:28px;gap:12px;text-align:center;color:var(--dp-muted);font-size:13px}.dp-empty h3,.dp-error-state h3{font-size:15px;color:var(--dp-fg);font-weight:600}.dp-empty p,.dp-error-state p{max-width:390px;line-height:1.7}.dp-state-icon{display:grid;place-items:center;width:42px;height:42px;border:1px solid var(--dp-line);border-radius:12px;background:var(--dp-soft);margin-bottom:2px}.dp-error-state .dp-state-icon{color:#bd633b}.dp-dialog .dp-notice{padding:9px 24px;background:var(--dp-soft);font-size:12px;color:var(--dp-muted)}
.dp-form-body{padding:4px 24px 22px}.dp-form label{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:8px 0;font-size:13px;font-weight:550}.dp-form label span{font-size:11px;font-weight:400;color:var(--dp-muted)}.dp-form :is(input,textarea){display:block;width:100%;font:14px/1.65 inherit;font-family:inherit;font-size:14px;line-height:1.65;color:var(--dp-fg);padding:10px 12px;border:1px solid var(--dp-line);border-radius:8px;background:var(--dp-bg)}.dp-form textarea{resize:vertical;min-height:140px;max-height:35dvh}.dp-form label[for=dp-content]{margin-top:20px}.dp-form [aria-invalid=true]{border-color:#bd4f45}.dp-dialog .dp-helper{color:var(--dp-muted);font-size:12px;margin-top:10px}.dp-dialog .dp-field-error{color:#bd4f45;font-size:12px;margin-top:6px}.dp-alert{margin-top:14px;padding:12px;display:flex;gap:10px;border:1px solid #bd4f4540;border-radius:8px;background:#bd4f4508;color:var(--dp-fg);font-size:12px}.dp-alert>svg{color:#bd4f45;margin-top:2px}.dp-alert p{margin:3px 0}.dp-alert small{color:var(--dp-muted)}
.dp-confirm{position:absolute;inset:0;background:color-mix(in srgb,var(--dp-bg) 92%,transparent);display:grid;place-items:center;padding:24px;z-index:2}.dp-confirm>div{max-width:350px;padding:24px;border:1px solid var(--dp-line);border-radius:12px;background:var(--dp-bg);box-shadow:0 12px 40px #0001}.dp-confirm h3{font-size:16px}.dp-confirm p{color:var(--dp-muted);margin:10px 0 20px}.dp-confirm>div>div{display:flex;gap:10px}.dp-spinner{width:22px;height:22px;border:2px solid var(--dp-line);border-top-color:var(--dp-accent);border-radius:50%;animation:dp-spin 1s linear infinite}
.dp-manage-list{margin-bottom:16px;border:1px solid var(--dp-line);border-radius:8px;padding:10px 12px}.dp-manage-list summary{cursor:pointer;font-size:12px;color:var(--dp-muted)}.dp-manage-row{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:10px 0;border-top:1px solid var(--dp-line);margin-top:8px}.dp-manage-row strong{font-size:13px;overflow-wrap:anywhere}.dp-actions{display:flex;gap:6px;flex-wrap:wrap}.dp-actions .dp-button{font-size:12px!important;padding:5px 8px}.dp-manage-actions{margin-top:20px}
@keyframes dp-enter{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:translateY(0)}}@keyframes dp-spin{to{transform:rotate(360deg)}}
@media(prefers-color-scheme:dark){.dp-dialog{--dp-bg:var(--dsw-alias-bg-layer-1,#23252a);--dp-soft:var(--dsw-alias-bg-layer-2,#2b2e34);--dp-fg:var(--dsw-alias-label-primary,#eef0f3);--dp-muted:var(--dsw-alias-label-secondary,#b0b5bf);--dp-line:var(--dsw-alias-border-primary,#414650)}}
@media(max-width:600px){.dp-dialog{width:calc(100vw - 24px);max-height:calc(100dvh - 24px)}.dp-header{padding:16px}.dp-toolbar{padding:0 16px 14px;flex-wrap:wrap}.dp-search{flex-basis:100%}.dp-tabs{padding:0 16px}.dp-workspace{grid-template-columns:1fr;height:auto;max-height:48dvh;overflow:auto}.dp-list{max-height:180px;border-right:0;border-bottom:1px solid var(--dp-line)}.dp-preview{max-height:230px;padding:16px}.dp-footer{padding:12px 16px;flex-wrap:wrap}.dp-form-body{padding:0 16px 18px}.dp-form textarea{max-height:30dvh}.dp-shortcut{font-size:10px}}
@media(prefers-reduced-motion:reduce){.dp-dialog,.dp-spinner{animation:none}.dp-dialog button{transition:none}}
`
